version: "3.8"
services:
  codex_database:
    image: mysql:8.1.0
    restart: unless-stopped
    container_name: codex-database
    ports:
      - "3360:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - codex-volume:/var/lib/mysql
    networks:
      - codex
networks:
  codex:
    driver: bridge
    name: codex-network
volumes:
  codex-volume:
